# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn ci:unit
      - name: Run E2E tests
        run: yarn ci:e2e
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Install Dependencies
        run: |
          yarn install
          npm install @vue/cli
      - name: Run ESLint
        run: npx vue-cli-service lint
      - name: Run Stylelint
        run: npx stylelint src/**/*.css src/**/*.vue src/**/*.scss
